version: '3'
services:
  mysql:
    container_name: minemysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: mineprestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network
    volumes:
      # # - type: bind
      # #   source: ./modules/testModule # local path to the module
      # #   target: /var/www/html/modules/testModule # path to be mounted in the container
      # # - type: bind
      # #   source: ./themes/myTheme # local path to the theme
      # #   target:  /var/www/html/themes/myTheme # path to be mounted in the container
      - psdata:/var/www/html
      # - ./img:/var/www/html/img
      # - ./template:/var/www/html/template
      # - ./themes:/var/www/html/themes
      # - ./classes:/var/www/html/classes
      - type: bind
        source: ./modules/testModule
        target: /var/www/html/modules/testModule
      - type: bind
        source: ./themes/myTheme
        target: /var/www/html/themes/myTheme
      - type: bind
        source: ./img
        target: /var/www/html/img
      - type: bind
        source: ./template
        target: /var/www/html/template
      - type: bind
        source: ./themes
        target: /var/www/html/themes
      - type: bind
        source: ./classes
        target: /var/www/html/classes
      - type: bind
        source: ./controllers
        target: /var/www/html/controllers
      - type: bind
        source: ./config
        target: /var/www/html/config
      - type: bind
        source: ./mails
        target: /var/www/html/mails
      - type: bind
        source: ./modules
        target: /var/www/html/modules
      - type: bind
        source: ./pdf
        target: /var/www/html/pdf



  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: minephpmyadmin
      networks:
        - prestashop_network
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - 8081:80

networks:
  prestashop_network:

volumes:
  psdata:
  dbdata: